language: go
cache:
  directories:
    - $DOWNLOAD_CACHE
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/btcsuite
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/github.com/grpc-ecosystem
    - $GOPATH/src/gopkg.in/alecthomas
    - $GOPATH/src/google.golang.org

# Remove Travis' default flag --depth=50 from the git clone command to make sure
# we have the whole git history, including the commit we lint against.
git:
  depth: false

go:
  - "1.14.x"

env:
  global:
    - GOCACHE=$HOME/.go-build
    - DOWNLOAD_CACHE=$HOME/download_cache

sudo: required

addons:
  apt:
    packages:
      - clang-format

jobs:
  include:
    - stage: Build
      script:
        - GO111MODULE=on make unit pkg=... case=_NONE_
        - GO111MODULE=on make lint workers=1
        - GO111MODULE=on make rpc-js-compile
    - stage: Test
      script: GO111MODULE=on make unit-race
      name: Unit Race
    # as long as the repo is private, we can't send coverage
    #- script: GO111MODULE=on make travis-cover
    #  name: Unit Cover

after_script:
  - LOG_FILES=./lntest/itest/*.log
  - echo "Uploading to termbin.com..." && find $LOG_FILES | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..." && tar -zcvO $LOG_FILES | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
